### ISSUE TITLE
How can I get the Epub Importer: Import epub to your vault command

### ISSUE THREAD

**Issue by OPEN1004MIND** [aoout/obsidian-epub-importer#1]
I even loaded it with BRAT and registered for Epub import (Add Beta plugin, 
but the command Epub Importer: Import epub to your vault doesn't come up when I Ctrl-P it. 

How can I get the Epub Importer: Import epub to your vault command to appear with Ctrl-P?

**Comment by aoout** [comment]
sorry, I can't reproduce this bug.
