### ISSUE TITLE
Support online image parsing

### ISSUE THREAD

**Issue by xiaoke1230** [aoout/obsidian-epub-importer#109]
![1730708343731](https://github.com/user-attachments/assets/f8d074d6-b748-40df-ba5a-d36693091eb6)

**Comment by xiaoke1230** [comment]
插件版本 0.4.2

**Comment by xiaoke1230** [comment]
![image](https://github.com/user-attachments/assets/46705059-ae5a-4f8b-883e-7e01b9c390db)
![image](https://github.com/user-attachments/assets/a091bae1-82b7-4d56-9423-f671ece9ae97)
现在情况是 图片除了封面生成，内容图片是没有生成的。

**Comment by aoout** [comment]
.epub 文件传给我

**Comment by aoout** [comment]
和报错无关，没有发生任何错误。
之所以看不到图片，是因为这本书里面的图片是在线的形式（我第一次遇到这么奇怪的书），解压之后发现里面根本没有任何图片文件。
而在线图片本来就不是一个本插件已经支持的特性。
所以，这还有待以后的更新。

**Comment by xiaoke1230** [comment]
好的 谢谢
