### ISSUE TITLE
NCX parsing fails when navpoint text nodes are empty

### ISSUE THREAD

**Issue by Untamed-Ambition** [aoout/obsidian-epub-importer#110]
# 情况
- obsidian我用的v1.7.6，在设置了目标书库后，选择书后没有任何反应
- 尝试了沙盒仓库，无法使用
- 尝试不设置书库路径，使用导入epub到库中命令，无法使用
- 尝试了将书库建立在obsidian内部，再输入绝对路径，无法使用
# 建议
- 有没有考虑到b站做个更详细的教程捏，只看到在油管有过demo教程

**Comment by aoout** [comment]
也许你可以打开插件的更多日志设置，然后看看控制台。

**Comment by Untamed-Ambition** [comment]
# 似乎是这个？
plugin:epub-importer:52 Uncaught (in promise) Error: failed to parse the .epub file
    at qs.init (plugin:epub-importer:52:5120)
    at async Ro.importEpub (plugin:epub-importer:61:17295)
    at async Xs.eval [as onSubmit] (plugin:epub-importer:61:14417)

# 下面是ai的解释（抱歉我不是很懂开发）
这个错误信息来自于Obsidian的一个插件——epub-importer，它用于将EPUB格式的电子书导入到Obsidian中。错误的具体内容解释如下：

1. **错误类型和位置**：
   - `Uncaught (in promise) Error`：这是一个在Promise中未被捕获的错误，意味着在异步操作（如文件解析）中发生了错误，但错误处理逻辑（如try-catch）没有正确捕获到这个错误。
   - `plugin:epub-importer:52`：错误发生在epub-importer插件的源代码的第52行。
   - `plugin:epub-importer:61`：后续的错误处理或相关操作发生在第61行。

2. **错误描述**：
   - `failed to parse the .epub file`：无法解析.epub文件。这通常意味着插件尝试读取或解析提供的EPUB文件时遇到了问题。

3. **函数调用栈**：
   - `qs.init`：在epub-importer插件的某个模块（可能是处理文件初始化的模块）中，`init`函数尝试执行某些操作，但失败了。
   - `Ro.importEpub`：这是一个异步函数，用于导入EPUB文件。它调用了`qs.init`函数，并可能处理了文件解析的逻辑。
   - `Xs.eval [as onSubmit]`：这看起来像是用户提交导入操作时的回调函数。它调用了`Ro.importEpub`函数来执行实际的导入操作。

### 解决步骤

1. **检查EPUB文件**：
   - 确保你尝试导入的EPUB文件是完整且未损坏的。
   - 尝试用其他EPUB阅读器打开文件，看是否能正常阅读。

2. **更新插件**：
   - 检查epub-importer插件是否有更新版本。有时候，插件的更新版本会修复旧版本中的bug。

3. **联系插件开发者**：
   - 如果问题依旧存在，可以考虑联系epub-importer插件的开发者，提供错误信息和你的EPUB文件作为参考，以便他们调查并修复问题。

4. **查看Obsidian的日志和控制台**：
   - 如前所述，打开Obsidian的开发者工具，查看控制台中是否有更详细的错误信息或警告。
   - 检查Obsidian的日志文件，看是否有与这个错误相关的条目。

5. **考虑其他导入方法**：
   - 如果epub-importer插件持续出现问题，你可以考虑将EPUB文件转换为其他格式（如PDF或Markdown），然后使用Obsidian支持的其他导入方法。

**Comment by Untamed-Ambition** [comment]
[Charlottes Web (E. B. White) (Z-Library).zip](https://github.com/user-attachments/files/17790935/Charlottes.Web.E.B.White.Z-Library.zip)
是这个文件（不知道是不是文件的原因？）（再次感谢您的开发）：）

**Comment by aoout** [comment]
是文件的原因。
