### ISSUE TITLE
大佬你这个更新版本有问题啊，ob死活停留在0.6.0，不停地提醒更新插件，点更新还是0.6.0

### ISSUE THREAD

**Issue by kiradzS** [aoout/obsidian-epub-importer#125]
%%please test the bug in a black vault first.
%%if there is something on console, please upload the screenshot.
卸载了再装还是这样版本号错误，强迫症患者要崩溃

**Comment by aoout** [comment]
非常抱歉，现在重新安装应该会好了。

**Comment by kiradzS** [comment]
成功了！
