### ISSUE TITLE
Won't Pull From This File

### ISSUE THREAD

**Issue by agentx216** [aoout/obsidian-epub-importer#15]
[Apologetics_ A Justification of - John M. Frame - Copy.zip](https://github.com/aoout/obsidian-epub-importer/files/13647628/Apologetics_.A.Justification.of.-.John.M.Frame.-.Copy.zip)

File is from above. The ePub was converted from a pdf but had other pdfs work fine. When imported, images will be exported but the text will just be a single bullet point of "Start" link. Link will only display:

        Cover
        
            @page {padding: 0pt; margin:0pt}
            body { text-align: center; padding:0pt; margin: 0pt; }
     

Great tool, regardless!

**Comment by aoout** [comment]
In fact, the plugin relies on epub's toc to work. So it cannot be processed for such epub.

**Comment by aoout** [comment]
From a functional perspective, without toc, the plugin cannot organize notes appropriately enough. From the perspective of demand, most epubs have the correct toc. Many epubs without the correct toc can actually be directly converted into txt documents, and there is no need for this plugin.

**Comment by aoout** [comment]
I just released the new version, now the log and notice will be more clear, maybe you can open the console and run the command `I just released the new version, now the log and notice will be more clear, maybe you can open the console`, see what the output will be and show me the screenshot so I can get more useful information.
