### ISSUE TITLE
about Indicator of Completion 

### ISSUE THREAD

**Issue by HarshIceHummer** [aoout/obsidian-epub-importer#16]
I want to ask if the process of importing the epub is really as quick as the Indicator shows?

Or is there any other background processing being done even after the Indicator of completion of importing the epub?

**Comment by HarshIceHummer** [comment]
I want to know this so that I can delete the epub file as soon as it has been imported.

**Comment by aoout** [comment]
Maybe something will be done in the background, but it has nothing to do with the original .epub file. The data has been transferred to a temporary folder, which will be automatically deleted when the task ends.

**Comment by HarshIceHummer** [comment]
Does this also means that I can import individual epubs back to back without having to worry that the processing of one temporary epub will not interfere with the processing of the other temporary epub?

**Comment by aoout** [comment]
What are your needs? Do you need to import many epub files in batches?The, you can use the `Import all epub from libraries to your vault` command.

**Comment by HarshIceHummer** [comment]
I have 130 epubs in my Library folder. Last time I tried importing all of them at once, only 5 got imported. So I'm importing all of them one by one.

**Comment by aoout** [comment]
> I have 130 epubs in my Library folder. Last time I tried importing all of them at once, only 5 got imported. So I'm importing all of them one by one.

It should be a bug, I will fix it.

**Comment by aoout** [comment]
> Last time I tried importing all of them at once, only 5 got imported. So I'm importing all of them one by one.

Did you encounter any bugs when you imported these epubs one by one? I'm wondering if it's because of a bug in the import of a certain epub that it never caused the entire command to terminate.

**Comment by HarshIceHummer** [comment]
As of now I haven't as I haven't completed importing all of them. If I
do, I'll be sure to report it to you. It's possible that there's an
issue with the structure of one of the epubs. Kindle also rejects
certain epubs if they are not properly encoded before they are sent to
the cloud storage. Therefore, sometimes I use this -
https://kindle-epub-fix.netlify.app/.

**Comment by aoout** [comment]
I just released the new version, now the log and notice will be more clear, maybe you can open the console and run the command I just released the new version, now the log and notice will be more clear, maybe you can open the console, see what the output will be and show me the screenshot so I can get more useful information.

**Comment by aoout** [comment]
I just released the new version, now the log and notice will be more clear, maybe you can open the console and run the command `Import all epub from libraries to your vault`, see what the output will be and show me the screenshot so I can get more useful information.
