### ISSUE TITLE
FR: 功能请求，关于 yaml 预设和一些细节

### ISSUE THREAD

**Issue by YIRU69** [aoout/obsidian-epub-importer#2]
你好，大大，在 discord 上就关注了你的插件，今天来使用了一番，真的很感谢你的付出，很好用

我在使用过程中，有一些建议和功能请求

1. 希望分隔的章节可以不在进行二次子文件夹划分：比如第二章节的小节，可以直接生成书籍的文件夹，然后加上第二章节的前缀
2. 按照生成的文章顺序添加序列号前缀
3. 可以指定导出文件的位置
4. 可以生成文件的开头预设 yaml ，便于管理
5. 图片等附件可以与obsidian的附件文件管理一致吗，直接转到ob的附件文件夹

这些建议基本是我导入一本书后，自己还要去做的工作，希望大大对上面有必要的有兴趣的可以添加一下功能，谢谢

**Comment by YIRU69** [comment]
另外想到，可以加入正则，对生成的文件进行正则替换，这样可以自己来规整格式

**Comment by YIRU69** [comment]
All Book 这个功能是否可以取消掉？

**Comment by aoout** [comment]
正则这个肯定不会有，直接用vscode不就好了吗

**Comment by aoout** [comment]
1. 你想要预设什么yaml？
2. 附件可以提供多种选择。
3. 可以加一个选择，决定分割到的具体粒度

**Comment by aoout** [comment]
前缀可以加。而且可以选择格式。
指定导出位置已经在计划中了。

**Comment by aoout** [comment]
all book放到发行版里其实是无心之失，以后肯定会有开关选项。

**Comment by aoout** [comment]
0.0.7更新了上面提到的一部分功能，不过我最近没什么时间，没怎么测试。

**Comment by YIRU69** [comment]
> 1. 你想要预设什么yaml？
> 2. 附件可以提供多种选择。
> 3. 可以加一个选择，决定分割到的具体粒度

就是一些通常的yaml 比如我的是：
```
---
id: "xxx"
title: xxx
fileClass: 
tags:
  - books
aliases: 
parent: "[[xxx]]"
status: 未读
type: 书籍
langr: xx
date modified: 2023-10-24 14:13:07
---
```

**Comment by YIRU69** [comment]
> 0.0.7更新了上面提到的一部分功能，不过我最近没什么时间，没怎么测试。

感谢感谢，有时间就看看，不耽误主要事情，现在其实大功能就很好了，我可以自己通过替换慢慢弄

**Comment by aoout** [comment]
忘了说，0.0.8更新了属性模板，提供了一些书籍元数据相关的变量可以使用。

**Comment by aoout** [comment]
附件位置可以通过变量完全自定义了。
至此，此issue中所提的全部功能请求都已经实现。
close it now.
