### ISSUE TITLE
无法提取第二层目录及以下的内容

### ISSUE THREAD

**Issue by yett1873** [aoout/obsidian-epub-importer#23]
[世说新语译注 - 刘义庆.epub.zip](https://github.com/aoout/obsidian-epub-importer/files/13837025/-.epub.zip)
![image](https://github.com/aoout/obsidian-epub-importer/assets/75569851/2ad5a6cb-9fb7-4cf4-b6e5-a3bd8577b0ca)
![image](https://github.com/aoout/obsidian-epub-importer/assets/75569851/ab244a78-a04a-4761-9d47-8c737cf0d780)

目前只有这本出现了问题，其它都正常，不知道是不是书的问题？

**Comment by aoout** [comment]
我没理解你说的意思。这本书有二层以及以上的目录吗？

**Comment by aoout** [comment]
在我看来，这本书的解析结果在0.2.6版本的epub importer似乎一切正常。
