### ISSUE TITLE
无法导入

### ISSUE THREAD

**Issue by TCM8840** [aoout/obsidian-epub-importer#25]
我在成功导入一本epub后，再也无法导入其他epub文件了。卸载重装也不成功。
[额尔古纳河右岸_副本.zip](https://github.com/aoout/obsidian-epub-importer/files/13916957/_.zip)

**Comment by aoout** [comment]
你所上传的这个文件，是你成功导入的那一本，还是之后无法导入的那一本？你之后是只尝试了一个文件无法导入，还是尝试了一些文件，都无法导入？

**Comment by TCM8840** [comment]
[伤寒论_9787117067249.zip](https://github.com/aoout/obsidian-epub-importer/files/13919841/_9787117067249.zip)这是成功的一本，之后试过很多其他文档，都没有成功导入，比如下面这几个：
[灵枢经_9787117067157.zip](https://github.com/aoout/obsidian-epub-importer/files/13919853/_9787117067157.zip)
[金匮要略.zip](https://github.com/aoout/obsidian-epub-importer/files/13919854/default.zip)

**Comment by aoout** [comment]
是不是上传错文件了，这本金匮要略根本不是.epub文件。

**Comment by TCM8840** [comment]
[黑天鹅_9787508616018.zip](https://github.com/aoout/obsidian-epub-importer/files/13926758/_9787508616018.zip)
[金匮要略_副本.zip](https://github.com/aoout/obsidian-epub-importer/files/13926759/_.zip)
这个是了，昨天那个金匮要略传错了。
我以为是和其他插件兼容性的问题，今天把其他第三方插件全部关闭，只保留importer一个插件，依然无法导入这些书籍

**Comment by aoout** [comment]
0.2.7版本已经可以正常导入：
1. 金匮要略
2. 伤寒论
3. 灵枢经
4. 黑天鹅

**Comment by aoout** [comment]
感谢你的支持与反馈。

**Comment by TCM8840** [comment]
可能是我用的Mac的原因，更新之后依然无法导入

**Comment by aoout** [comment]
抱歉。我再看看。

**Comment by TCM8840** [comment]
是我的问题，没说清楚，辛苦开发者，感谢

**Comment by aoout** [comment]
可以麻烦你更新到0.2.8，打开该插件内`moreLog`设置，打开控制台再尝试导入一次吗，把得到的信息截图给我看下。

**Comment by TCM8840** [comment]
<img width="881" alt="图片" src="https://github.com/aoout/obsidian-epub-importer/assets/134826124/4624899f-e09c-4da8-b9b2-60b797f74584">
尝试导入之前上传的epub，控制台没有数据刷新，插件配置如图

**Comment by aoout** [comment]
你的保存路径怎么这么奇怪...那真的还在obsidian的库里吗

**Comment by TCM8840** [comment]
设置的绝对路径，设置成下面这样也不成功
<img width="884" alt="图片" src="https://github.com/aoout/obsidian-epub-importer/assets/134826124/241a706b-494a-4a03-96ad-181c64b17e23">
<img width="886" alt="图片" src="https://github.com/aoout/obsidian-epub-importer/assets/134826124/1825bedd-0fef-4c8e-b44f-7bdc4a98ad0a">

**Comment by aoout** [comment]
控制台仍然没有任何东西吗

**Comment by TCM8840** [comment]
您需要看控制台哪部分信息，可以给我截个图吗

**Comment by aoout** [comment]
![image](https://github.com/aoout/obsidian-epub-importer/assets/60838705/b8be05e5-03fe-4fca-97c0-72307bcd43f2)

**Comment by aoout** [comment]
格式大概就是这样

**Comment by TCM8840** [comment]
是这个吗？在使用导入命令，尝试导入《额尔古纳河右岸》时出现的信息:
<img width="557" alt="图片" src="https://github.com/aoout/obsidian-epub-importer/assets/134826124/c0b2b56e-a237-464a-b033-2a26ec322ead">

**Comment by aoout** [comment]
> 我在成功导入一本epub后，再也无法导入其他epub文件了。卸载重装也不成功。

这里说的成功的导入是什么情况？现版本依旧可以成功导入吗？那个.epub文件呢？

**Comment by TCM8840** [comment]
之前上传的文件中，《伤寒论》是成功导入的（0.2.6版本），其他均不能导入。今天删去之前导入成功的文件夹，尝试使用0.2.8导入《伤寒论》，控制台是这样的：
<img width="544" alt="图片" src="https://github.com/aoout/obsidian-epub-importer/assets/134826124/05681534-43dd-4cee-a88e-08c7efcb7d88">

**Comment by TCM8840** [comment]
之前上传的文件中，《伤寒论》是成功导入的（0.2.6版本），其他均不能导入。今天删去之前导入成功的文件夹，尝试使用0.2.8版本重新导入《伤寒论》，控制台是这样的：
<img width="546" alt="图片" src="https://github.com/aoout/obsidian-epub-importer/assets/134826124/2b314656-286d-438e-90b8-e1eb71009a1a">

**Comment by TCM8840** [comment]
我尝试新建了一个测试仓库，只安装0.2.8版插件，无其他第三方插件，上面这些书又都可以成功导入。
<img width="537" alt="图片" src="https://github.com/aoout/obsidian-epub-importer/assets/134826124/9df1246e-4fb5-485f-964f-2f9f55e6405e">
所以，是不是与其他插件冲突的原因呢？这些是我安装的插件：
<img width="200" alt="图片" src="https://github.com/aoout/obsidian-epub-importer/assets/134826124/0bed0fb6-1911-44d2-bb83-6689f8550f0b">

**Comment by aoout** [comment]
或许有可能是因为插件冲突。可以发一下原本的库的.obsidian/plugins文件夹吗。如果真的是插件冲突，我大概也没什么办法，只能二分法排查。

**Comment by TCM8840** [comment]
为了节省您的时间，我逐一排查了已安装的插件，发现无法和Local image plus插件同时使用，在测试库中只安装这两个插件也会报错。测试库供您参考：
[ceshi.zip](https://github.com/aoout/obsidian-epub-importer/files/13996017/ceshi.zip)

**Comment by aoout** [comment]
我在自己的库里安装了Local image plus，发现没有任何问题。下载了你提供的库，又会报错了。接着，我把你的库里`.obsidian\plugins\obsidian-local-images-plus-0.15.9`移出去，从官方商店重新下载Local image plus之后。又是没有任何问题了。然后删掉该插件，把刚刚移出去的文件夹移回来，还是有问题。
你的插件是在官方商店下载的吗？为什么不一样？

**Comment by aoout** [comment]
你提供的测试库里的Local image plus插件，和我从官房商店下载的Local image plus的代码甚至都不一样。有一处小小的不同，恰恰是这个不同，导致了最后的错误。
![image](https://github.com/aoout/obsidian-epub-importer/assets/60838705/b6c249e9-4b44-4d49-97e7-069a45ab2c17)

**Comment by aoout** [comment]
我去看了Local image plus的issue#47，大概就是在说这里的问题。我的猜测是这个插件在github上的文件曾经被替换过一次，而你所使用的是旧版本。
