### ISSUE TITLE
几个建议：抛弃图片、保存路径更详细、属性模板允许为空

### ISSUE THREAD

**Issue by jxjxjhjh** [aoout/obsidian-epub-importer#26]
1、抛弃图片

很多书的图片其实是没有必要的，希望增加抛弃图片的设定

2、保存路径更详细

目前是强制生成 书名文件夹 的，希望能够不生成 书名文件夹，例如 BOOK/金瓶梅.MD BOOK/小岛经济学.MD 更简洁。

3、属性模板允许为空

属性模板的设置中，如果有一项为空，例如
书名: 
是无法正常导入书籍的，冒号后面必须有内容，例如
书名: 金瓶梅

**Comment by aoout** [comment]
我不太理解，你说的图片没有必要的书是什么样子的？为什么要抛弃图片？

**Comment by aoout** [comment]
> 3、属性模板允许为空
属性模板的设置中，如果有一项为空，例如
书名:
是无法正常导入书籍的，冒号后面必须有内容，例如
书名: 金瓶梅

我刚刚测试了一下，使用这个属性模板是没问题的：
```
title: 
author: {{author}}
```
效果为：

![image](https://github.com/aoout/obsidian-epub-importer/assets/60838705/21ac87c7-e063-4a76-8a1c-fa95f0a301df)

**Comment by aoout** [comment]
参照你的需求，我觉得你可能更加需要的是一个epub2txt的工具。就是没有图片，并且全部内容在一个文件里的。这是我个人的建议。如果有意愿的话，欢迎与我讨论关于阅读工作流的问题。

**Comment by aoout** [comment]
> 希望能够不生成 书名文件夹

已经实现。
