### ISSUE TITLE
Bug: 一些 epub 的书籍，经过插件后，分隔出来的文件是空文件

### ISSUE THREAD

**Issue by YIRU69** [aoout/obsidian-epub-importer#3]
一些 epub 的书籍，经过插件后，分隔出来的文件是空文件

我测试了一下，是某一些的书籍

比如 
[洞见：从科学到哲学，打开人类的认知真相.zip](https://github.com/aoout/obsidian-epub-importer/files/13161681/default.zip)
`需要更改后缀为epub`

这个导入错误的原因是什么呢？
怎么知道哪些书籍是导入不成功的呢

**Comment by YIRU69** [comment]
我刚找到了一个可以分隔的不错的程序，你可以看看， 测试了洞见这本书是可以的

**Comment by aoout** [comment]
It is a bug.
最新版本已经修复了。

**Comment by aoout** [comment]
> 怎么知道哪些书籍是导入不成功的呢
我不能理解这句话是什么意思。如果有一个文件导入不成功，要么是因为bug，要么是因为其格式并不符合一般的epub，目前的代码还无法解析。解析epub我没有用任何库或者抄代码，全是我自己写的，所以进展比较慢，出现bug的几率也比较大。

**Comment by aoout** [comment]
> 我刚找到了一个可以分隔的不错的程序，你可以看看， 测试了洞见这本书是可以的
> 
> https://github.com/ChandlerVer5/epub2MD

谢谢。有机会我会参考的。不过目前阶段对我应该是没什么帮助。
