### ISSUE TITLE
层级深度数值比显示数值大一

### ISSUE THREAD

**Issue by jxjxjhjh** [aoout/obsidian-epub-importer#31]
0.2.7版本的设置中，层级深度 设置为0是无效的
另外，层级深度是否还有效我无法确定，似乎无论是1级还是5级都没什么变化，不过这点我无法确定。

**Comment by aoout** [comment]
层次深度所设定的范围并不是全部都要有效果的。比如说如果.epub目录本来就只有2级，那么对于插件来说，设置为2级深度和3级深度自然就是一样的。

**Comment by aoout** [comment]
fix it by #35.

**Comment by aoout** [comment]
@jxjxjhjh https://github.com/aoout/obsidian-epub-importer/releases/tag/0.3.1-beta.1
