### ISSUE TITLE
图片格式选择第三种时部分图片和脚注解析会出错

### ISSUE THREAD

**Issue by DanShui-Yu** [aoout/obsidian-epub-importer#34]
错误姿势包括但不限于

![image](https://github.com/aoout/obsidian-epub-importer/assets/69069739/1d063fe5-b03e-49c4-986c-da73aacf944c)
![image](https://github.com/aoout/obsidian-epub-importer/assets/69069739/1861729f-fc73-4a6b-ad40-5c37ef29f38a)
![image](https://github.com/aoout/obsidian-epub-importer/assets/69069739/05d30e88-2dde-4d52-a685-495578753f3c)
![image](https://github.com/aoout/obsidian-epub-importer/assets/69069739/69df9bc4-1dd8-4cf2-b9a5-fbd8c878d0c8)
![image](https://github.com/aoout/obsidian-epub-importer/assets/69069739/429ea51b-c6a4-4da5-acf8-3f98cdf639a6)
![image](https://github.com/aoout/obsidian-epub-importer/assets/69069739/548dd592-f2af-48ae-979a-8a448827d588)

![image](https://github.com/aoout/obsidian-epub-importer/assets/69069739/819d1f84-d117-4dbe-8d8b-c682ca6fc17e)

**Comment by aoout** [comment]
太过于鬼畜了。正则表达式真是麻烦。

**Comment by PupupupuTong** [comment]
如果选第二种格式好像更多是漏掉

![image](https://github.com/aoout/obsidian-epub-importer/assets/69069739/5fc8c8b8-c120-432b-b86f-7b5e32a335ee)

**Comment by aoout** [comment]
fixed in https://github.com/aoout/obsidian-epub-importer/commit/b5338fb9a49671658e9863e420eb3fb0f8d69e7e.

**Comment by PupupupuTong** [comment]
好了很多，但还是有😂
![image](https://github.com/aoout/obsidian-epub-importer/assets/69069739/de709055-1ff9-48b8-bb45-989c96cc79f1)
![image](https://github.com/aoout/obsidian-epub-importer/assets/69069739/ca64e1e4-5382-4b7d-94c1-b0c26499d6f5)

丢脚注也是

![image](https://github.com/aoout/obsidian-epub-importer/assets/69069739/313b2cee-6f27-4d79-bf62-779ea89baa4b)
![image](https://github.com/aoout/obsidian-epub-importer/assets/69069739/785ae44e-44a6-4091-b6c6-8f6c05ac3549)
![image](https://github.com/aoout/obsidian-epub-importer/assets/69069739/03234e5d-4692-4e4c-beff-051fe5ced998)

**Comment by aoout** [comment]
图片格式选择的第三个选项吧，第二个现在是正常的。
![image](https://github.com/aoout/obsidian-epub-importer/assets/60838705/03e1eef3-49f3-40b6-a3a8-9f7fa0b60560)

**Comment by aoout** [comment]
fixed in https://github.com/aoout/obsidian-epub-importer/commit/efbefd1a6def64408519c4b1331edff5e8b20a85.

**Comment by aoout** [comment]
第三种图片格式现在几乎也没什么用，就先不发新版本了。

**Comment by PupupupuTong** [comment]
有道理。但是脚注丢失还是有

![image](https://github.com/aoout/obsidian-epub-importer/assets/69069739/3fe978c2-7720-4790-8fe4-f577f5d2d44c)

**Comment by aoout** [comment]
![image](https://github.com/aoout/obsidian-epub-importer/assets/60838705/4ef1f84c-78e6-46c7-bbf6-e469d1969c92)
我这边没有这个问题哦。

**Comment by PupupupuTong** [comment]
不能这样看，你切换一下视图试试，会发现末尾脚注的序号不一样。阅读视图下它是按实际脚注数量计数的，漏掉的都被直接递补了，我是用了蚕子大大开发的信息列表插件，所以才能一眼看出来中间少了
[ZH 信息列表0.9.zip](https://github.com/aoout/obsidian-epub-importer/files/14032186/ZH.0.9.zip)

**Comment by aoout** [comment]
你看我发的截图，别看序号，看文本。我发的截图里应该是没有漏掉东西的。

**Comment by aoout** [comment]
> 又试了个新的测试员，脚注仍有跳转问题


能添加一些更多的信息吗，我不是很能理解，什么叫做脚注有跳转问题。

**Comment by aoout** [comment]
@DanShui-Yu 你好，关于这个问题还有什么想要补充的吗？

**Comment by DanShui-Yu** [comment]
> [医学史通识丛书重构秦汉医学图像 (廖育群) .txt](https://github.com/aoout/obsidian-epub-importer/files/14082734/default.txt)

这本书现在无法导入了，执行命令没反应

**Comment by aoout** [comment]
@DanShui-Yu 这个文件名最后是一个空格，把空格删掉就好了

**Comment by DanShui-Yu** [comment]
哦哦，成功了，但脚注果然还是有问题，都识别成文档链接了

**Comment by DanShui-Yu** [comment]
表格也有点小毛病

![image](https://github.com/aoout/obsidian-epub-importer/assets/69069739/11d2fef6-4fb8-48f1-b340-f795565eccac)

我感觉这些非标准格式的内容可能会有很多种类型，想统一适配比较困难，或许可以考虑以额外选项的形式解决？导入的时候就弹窗要求选择该书的脚注样式什么的

**Comment by aoout** [comment]
> 哦哦，成功了，但脚注果然还是有问题，都识别成文档链接了

这个不是epub importer识别的，而是本来书里面写的就不是标准的脚注，而是链接啊

**Comment by aoout** [comment]
也就是 https://github.com/aoout/obsidian-epub-importer/issues/13

**Comment by DanShui-Yu** [comment]
> 表格的问题是说多出几个空行吗

不是，第一行【姓名】【所业之事】应该是表头才对。这本书里的

> 这个不是epub importer识别的，而是本来书里面写的就不是标准的脚注，而是链接啊

好吧，但理论上来说它应该是脚注，能转化就好了
