### ISSUE TITLE
优化包含换行符的标题的显示效果

### ISSUE THREAD

**Issue by DanShui-Yu** [aoout/obsidian-epub-importer#36]
欢迎我们的老测试员

![image](https://github.com/aoout/obsidian-epub-importer/assets/69069739/0e975d55-b7aa-4839-ab97-2516011a8f8e)
![image](https://github.com/aoout/obsidian-epub-importer/assets/69069739/635c4f76-8811-4991-8b43-30817ee9dea1)

**Comment by aoout** [comment]
一纸东晋史，两行辛酸泪

**Comment by aoout** [comment]
而且HTML2Markdown的解析是Obsidian内置的，所以我也很难去改。

**Comment by PupupupuTong** [comment]
昂，其实是小问题，毕竟只有一级标题受难，手动改一下没什么麻烦的，但好像之前的版本没这毛病（当然也可能是我没注意）。或许可以改成凡是标题文本都忽略中间的换行符？

**Comment by PupupupuTong** [comment]
话说大大你改 title 是不是打错字了

**Comment by aoout** [comment]
> 昂，其实是小问题，毕竟只有一级标题受难，手动改一下没什么麻烦的，但好像之前的版本没这毛病（当然也可能是我没注意）。或许可以改成凡是标题文本都忽略中间的换行符？

不可能之前版本没这毛病，绝对是一样的。这本书自己的格式特殊而已。

**Comment by aoout** [comment]
> 话说大大你改 title 是不是打错字了

是的。谢谢。

**Comment by aoout** [comment]
问题是在自己的标题里加上换行符的书本来就少之又少，只有个别的特例。所以做这个的优先级很低。
