### ISSUE TITLE
apsolute path doesn't work on different OSs

### ISSUE THREAD

**Issue by simonfossom** [aoout/obsidian-epub-importer#40]
- macos has paths like this: /Users/MyName/vault/
- Android will have the same problem: /storage/emulated/0/vault

Please, change the paths so they are relative to the vault root.

**Comment by aoout** [comment]
This plugin is not available for Android.

**Comment by simonfossom** [comment]
will it work on macos?

**Comment by aoout** [comment]
According to https://github.com/aoout/obsidian-epub-importer/issues/25, I think it will work on macos.

**Comment by simonfossom** [comment]
sorry for the late reply - IT WORKS!
I was waiting for this plugin forever. 

I appreciate you making this so much! 
Thank you! 🙏
