### ISSUE TITLE
（题外话）大佬考虑将“打开文档时自动在侧栏打开包含它的moc并锁定页面”功能单独剥出来做一个插件吗？

### ISSUE THREAD

**Issue by DanShui-Yu** [aoout/obsidian-epub-importer#42]
最近正在头疼长文档（百万字级别）拆分后难以在子文档使用过程中查看原书目录结构的问题，理想中的工具是一个**能够显示自定义全文件夹树状结构且能像quiet outline那样随当前打开文档展开收缩的侧栏**，这时突然想起大佬的epub导入插件似乎基本包含了主要功能，故特此询问

**Comment by aoout** [comment]
合理。我可以考虑考虑

**Comment by aoout** [comment]
但是拆出来功能太简陋了，我也没有能力在这个特性上持续开发，也很难办。

**Comment by aoout** [comment]
想了想还是直接用这个插件的本体吧，貌似也没什么不好的
