### ISSUE TITLE
图片解析

### ISSUE THREAD

**Issue by TryoneBest** [aoout/obsidian-epub-importer#45]
这是我的界面截图，导入正常完成没有报错，但是图片全部显示不出来
![image](https://github.com/aoout/obsidian-epub-importer/assets/42643863/b0a92fa9-c380-4e18-aac8-81764499a949)
[罗生门_芥川龙之介_RyunosukeAkutagawa.zip](https://github.com/aoout/obsidian-epub-importer/files/14812126/_._RyunosukeAkutagawa.zip)
zhe
[月亮和六便士_W.SomersetMaugham_傅惟慈.zip](https://github.com/aoout/obsidian-epub-importer/files/14812127/_W.SomersetMaugham_.zip)
这两本epub都出现了解析出来的图片失效的问题

**Comment by aoout** [comment]
It cannot be reproduced in version 0.3.1.
