### ISSUE TITLE
convert urls to markdown links not wiki links

### ISSUE THREAD

**Issue by zsviczian** [aoout/obsidian-epub-importer#51]
In the book I converted urls were converted to wiki links like this `[[https://the.url|alias]]`. In quick switcher Obsidian picked these up as pages that could be created in my vault. Instead it would be great if urls could be converted to markdown links `[alias](https://the.url)`

**Comment by aoout** [comment]
Can you please show relevant screenshots?

**Comment by zsviczian** [comment]
![image](https://github.com/aoout/obsidian-epub-importer/assets/14358394/11134924-de45-4416-a153-56b5eadb5ee4)

[text00033.zip](https://github.com/aoout/obsidian-epub-importer/files/14965801/text00033.zip)

**Comment by aoout** [comment]
Maybe you can do this conversion through other plugins?

**Comment by zsviczian** [comment]
sure I could... but why not do the post-processing in one go? I'd rather avoid using additional plugins making the whole process more complicated and more fragile...

This regular expression will capture the link and the alias. you can easily convert this into markdown links so they are correctly handled by Obsidian `/\[\[(https:\/\/[^\]]*?)]]/g`
