### ISSUE TITLE
标题中存在/情况的解析

### ISSUE THREAD

**Issue by MiSanl** [aoout/obsidian-epub-importer#55]
%% please request one feature in one issue.
＃ Why I need the feature
当标题存在`/`或者`\`符号时，尤其是计算机网络相关的书籍，标题中很容易出现这种字符，现在会将其视为路径分割符，导致文章标题的不完整。是否可以考虑增加设置选项来改变这种行为呢？

比如当标题中遇到`/`时将其替换为`-`或其他可以作为文件名的字符。
当然其他的特殊字符如`:`还没遇到过，不清楚目前是怎么处理的。

**Comment by aoout** [comment]
![image](https://github.com/aoout/obsidian-epub-importer/assets/60838705/7bb1eb23-9fd4-42ce-b8e0-ad8226da7267)

**Comment by aoout** [comment]
我使用了"&"符号把title中的斜杠和反斜杠都替换了
