### ISSUE TITLE
Creates notes but all of the notes are empty

### ISSUE THREAD

**Issue by Archie-2021** [aoout/obsidian-epub-importer#63]
I just tested this plugin on a empty (test/sandbox) vault and it created moc and notes very good, but on both of two my tests all the notes it creates are empty. and in console it just says it imported the book successfully.

![image](https://github.com/aoout/obsidian-epub-importer/assets/85870778/955aba6a-ef9f-417e-8d09-1aaa258176b9)

![image](https://github.com/aoout/obsidian-epub-importer/assets/85870778/fa3cc800-b447-44dd-9122-63c4ce48961c)

I am using Linux, maybe that is an issue.

Have been looking to see such a plugin for such a plugin for a long time. I used to convert books manually using pandoc, and it was such a pain (so much that I gave up). Hope to see it fully functinal soon.

**Comment by aoout** [comment]
I don't know what I can do for linux, I have no way to debug on it. Maybe I will do something, after I know more about linux, or someone else is willing to help me.

**Comment by Archie-2021** [comment]
> I don't know what I can do for linux, I have no way to debug on it. Maybe I will do something, after I know more about linux, or someone else is willing to help me.

I guess it is the issue, but I am not sure as I don't know what method your plugin uses to convert the notes. It seems like it can find the file and do a lot of conversion. I mean it should not be a necessity for a plugin developer to deal with this, because Obsidian/Electron is cross platform and don't depend on an specific OS

**Comment by Archie-2021** [comment]
> Anyway, I wanted to confirm first that this is indeed a platform difference. Please upload the corresponding .epub file so that I can test it on windows.

Sure , here is the link: https://file.io/6VUvdoDI4BTo

**Comment by olterman** [comment]
I have the same issue on Linux with 104 different books

**Comment by olterman** [comment]
Hey, so I did some debugging (rather just inserted som breakpoints) and it tries to stat a file that has a filename made from both the exec path and the actual vault path ... see screenshot ... hope this helps 
![Screenshot_24-May_13-30-41_14761](https://github.com/aoout/obsidian-epub-importer/assets/40863714/4720577c-7a03-4c4b-bd2b-c429da830114)

**Comment by aoout** [comment]
@olterman 
Can I see your settings for this plugin?

**Comment by olterman** [comment]
sure 

![Screenshot_24-May_20-23-07_12384](https://github.com/aoout/obsidian-epub-importer/assets/40863714/2db8df66-42ab-446f-beb4-cb4ffe96788a)

**Comment by aoout** [comment]
I tested version 0.6.1 on Ubuntu and everything worked fine. So I decided to close this issue.
