### ISSUE TITLE
No image file is created 

### ISSUE THREAD

**Issue by OPEN1004MIND** [aoout/obsidian-epub-importer#7]
![z01](ePUB/EPUB FILE NAME/images/z01.png

The MD file has information about the Image file, but the directory is not created and the file is not created too.
Is it because it's a PNG file?
How can I make sure that the image file is also created in the directory I set?

After testing a few books ....
Some books create (jpg) images and some don't. 
Some books have content and some don't.
I don't know if each book has a characteristic, but the current version has some that do and some that don't.

But thank you for developing it, trusting that it will be improved in the future.

**Comment by aoout** [comment]
show the file with bug.
like https://github.com/aoout/obsidian-epub-importer/issues/6

**Comment by aoout** [comment]
No reply for too long.
Reopen the issue when you want to continue the conversation.
