### ISSUE TITLE
一些epub文件导入后标题异常

### ISSUE THREAD

**Issue by ZouDongj** [aoout/obsidian-epub-importer#70]
如图
![image](https://github.com/aoout/obsidian-epub-importer/assets/41882825/885f3586-5b6e-4b17-8967-c3b1d4141fab)
[算法图解 (巴尔加瓦 (Aditya Bhargava)).zip](https://github.com/user-attachments/files/15535978/Aditya.Bhargava.zip)

而且好像还会把一些文本中的#识别成标题
![image](https://github.com/aoout/obsidian-epub-importer/assets/41882825/1f786d63-ac45-4c77-b347-73efa097a449)

**Comment by aoout** [comment]
很抱歉，但是我不建议你使用本插件导入代码类的书籍。其中这之中需要做的东西实在是太复杂了。
我个人建议对于这类书籍使用pdf格式观看。
