### ISSUE TITLE
这本资治通鉴导入后没有内容

### ISSUE THREAD

**Issue by dlsdgj** [aoout/obsidian-epub-importer#71]
https://pan.xj.hk/s/e9c41d
![image](https://github.com/aoout/obsidian-epub-importer/assets/20112812/3785e6be-1609-4e4b-90fa-0fb3437f93a8)

**Comment by aoout** [comment]
很抱歉，可能因为时隔太久了，已经过期了，能重新发一次吗

**Comment by dlsdgj** [comment]
这些都是没能导入的
![image](https://github.com/aoout/obsidian-epub-importer/assets/20112812/28e2380c-3d78-4c12-89b3-4b9a76a04675)

https://pan.xj.hk/s/d3ac76

**Comment by aoout** [comment]
两晋之乱的问题，在这里已解决：https://github.com/aoout/obsidian-epub-importer/issues/78

**Comment by aoout** [comment]
郁达夫小说全集的问题，在这里已解决：https://github.com/aoout/obsidian-epub-importer/issues/80

**Comment by aoout** [comment]
黑书已经可以正常导入。

**Comment by aoout** [comment]
纳尼亚传奇已经可以正常导入。

**Comment by aoout** [comment]
资治通鉴已经可以正常导入。
