### ISSUE TITLE
Ignore spaces around file names

### ISSUE THREAD

**Issue by JuanBingDaWang** [aoout/obsidian-epub-importer#73]
开发者您好：非常感谢您开发的插件，解决了我多端同步阅读电子书的需求。目前我这里遇到的问题是，系列图书中有一本无法导入，但本系列其他书目的导入是正常的。此外，在已经导入的书目中，存在文章内容不分段的现象。
在我所上传的.zip文件中，参考周刊1和参考周刊2可以正常导入，但内容不分段；参考周刊3无法导入，具体表现为运行后没有反应和后续提示。
再次对您的开发表示感谢。
[参考周刊.zip](https://github.com/user-attachments/files/15949704/default.zip)

**Comment by aoout** [comment]
这是一个乌龙。因为你的参考周刊的文件名最后是一个空格（你发现了吗？这可能很难看到）。

**Comment by aoout** [comment]
我后续会做一些优化，让插件忽略这些空格。

**Comment by JuanBingDaWang** [comment]
感谢您，确实是由于文件名最后是一个空格导致的！~

**Comment by aoout** [comment]
我看了一下，你发的文件解析后排版全是混在一起的，特别乱。刚刚更新了再格式化的功能。
![image](https://github.com/user-attachments/assets/28fb3d3b-a05b-46b3-894d-d4dd9095fc69)
效果如图所示。需要在设置里开启reformatting选项。

**Comment by JuanBingDaWang** [comment]
好的好的，太感谢了！我之前一直是手动替换换行符实现的换行，这样确实方便了很多。我已经尝试了最新的版本，在我这里运行也是理想的，感谢！
