### ISSUE TITLE
only got the first chapter

### ISSUE THREAD

**Issue by thisisfine-046** [aoout/obsidian-epub-importer#8]
So I have been test some epub on these sample epub https://idpf.github.io/epub3-samples/30/samples.html, some of them work flawless, some isn't.

For example this one  [huatien.zip](https://github.com/aoout/obsidian-epub-importer/files/13460126/huatien.zip)

Only got extracted the first chapter, the introduce one. 

Overall, great start! Hope to see this keep getting improve.

**Comment by aoout** [comment]
It sounds like you're doing this for just testing purposes?
while, the file you gave point to a very simple bug, what a careless mistake.

**Comment by aoout** [comment]
fixed in https://github.com/aoout/obsidian-epub-importer/commit/1a058181fa1de7bed3a8e434eaa0d01463bf9462.
