### ISSUE TITLE
导入后无反应，报错

### ISSUE THREAD

**Issue by asa-world** [aoout/obsidian-epub-importer#87]
点击某一本书导入后无反应，控制台报错，求解答
![image](https://github.com/aoout/obsidian-epub-importer/assets/86909426/5f018522-0398-420b-9a82-5f831c272005)

**Comment by aoout** [comment]
上传对应.epub文件

**Comment by asa-world** [comment]
[TheEconomist.2024.07.06.zip](https://github.com/user-attachments/files/16116275/TheEconomist.2024.07.06.zip)

**Comment by asa-world** [comment]
> 上传对应.epub文件

已上传

**Comment by bennyyip** [comment]
应该是0.3.6的问题，我试了几个EPUB都失败了。回退0.3.5就好了。

**Comment by aoout** [comment]
你在使用哪个版本？我在0.3.6版本下可以成功导入。

**Comment by aoout** [comment]
> 应该是0.3.6的问题，我试了几个EPUB都失败了。回退0.3.5就好了。

很抱歉造成体验上的倒退。能请你打开对应的issue提供反馈吗？

**Comment by bennyyip** [comment]
obsidian 1.6.5，Windows
我看了眼控制台是parse opf的xml出错了

**Comment by aoout** [comment]
@bennyyip 请问你的obsidian安装程序版本是？

**Comment by aoout** [comment]
我已经复现了。做法是将安装程序更新到v1.6.5。
而在v1.5.12上，是不存在这个bug的（此时Obsidian本体的版本也为v1.6.5）。
