### ISSUE TITLE
failed on import and some other issue

### ISSUE THREAD

**Issue by keno-log** [aoout/obsidian-epub-importer#9]
thanks for the work!
attached is a book of a series of books, I got below issues:
1/the final md file is blank after imported
这本书导入后md文件内容为空，同系列另一本就能正常import并显示；
2/the md file name is the "Author" instead of "title", this hapened to other series books too. md文件名显示为作者名字，而非图书名字，同系列图书都有同样问题。it will block books from the same series due to the same md file name. 重名的话同系列其他图书就无法再上传
3/it also failed to be recorded in the Allbooks.md

some function suggestion
1/when granularity=0, there will be only 1 md file, is it possible to add tags of author and series name, this will helps a lot to backlink.
为md文件添加tags，可有利反链，对系列图书或者同一作者图书相关联有很大帮助
2/batch import for EPUBs from the same file 同文件夹图书批量import

thanks!
[Gary D. Schmidt - [Wednesday Wars 01] - The Wednesday Wars.zip](https://github.com/aoout/obsidian-epub-importer/files/13539283/Gary.D.Schmidt.-.Wednesday.Wars.01.-.The.Wednesday.Wars.zip)

**Comment by keno-log** [comment]
thanks, I found "Propertys template", but only when granularity=1, "Propertys template" shows in granularity level 1 md file.
when granularity=0, the only one md file has no Propertys.

**Comment by aoout** [comment]
> the final md file is blank after imported

I don't know why Obsidian's `htmlToMarkdown` function return the blank, but I will convert it to plaintext in https://github.com/aoout/obsidian-epub-importer/commit/5277d69d4054500384372815529b49ac04b4502c.

**Comment by aoout** [comment]
> 同文件夹图书批量import

implemented in https://github.com/aoout/obsidian-epub-importer/commit/57595ac1c6d1b5efdefcda41030170be02ddf606.
