### ISSUE TITLE
Empty HTML tables cause conversion to markdown to fail

### ISSUE THREAD

**Issue by ekarious** [aoout/obsidian-epub-importer#94]
Hello, 

I encountered a bug when importing an `epub` file.

Here is the image
![Obsidian_WxPx296jW0](https://github.com/user-attachments/assets/3bf2ef97-d543-4cf4-855c-c217ee77ed50)

As you can see, the temp folder is created and it first glance, everything seams correct inside.
The first array avec 130 items.
The toc array only 129, don't know if this is relevant.

**Comment by aoout** [comment]
please upload the .epub file

**Comment by ekarious** [comment]
You can find the file here: 
https://mega.nz/file/Mq4n0LSJ#RweYoE1WZrEFwuFEoYanAPDGY3HuM801EpZPZN_l6dg

**Comment by aoout** [comment]
![image](https://github.com/user-attachments/assets/a777b70c-1601-4cfd-97a6-1e58e0c74d4d)
I have found the part that is causing the problem. However, the processing here is done by Obsidian API's  `htmlToMarkdown` function

**Comment by ekarious** [comment]
Yes I also notice that the first sentence is not between the `<p></p>` tags.
Thank you for the fix.
